import { execSync } from 'child_process';

export interface GitOptions {
  projectPath: string;
  createMR?: boolean;
  mrTitle?: string;
  mrDescription?: string;
}

export interface GitResult {
  success: boolean;
  branch?: string;
  commit?: string;
  mrUrl?: string;
  message?: string;
}

export function isGitRepository(projectPath: string): boolean {
  try {
    execSync('git rev-parse --git-dir', {
      cwd: projectPath,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

export function getCurrentBranch(projectPath: string): string {
  try {
    return execSync('git branch --show-current', {
      cwd: projectPath,
      encoding: 'utf-8',
    }).trim();
  } catch {
    return 'main';
  }
}

export function getRemoteUrl(projectPath: string): string | null {
  try {
    const url = execSync('git remote get-url origin', {
      cwd: projectPath,
      encoding: 'utf-8',
    }).trim();
    return url;
  } catch {
    return null;
  }
}

export function createBranch(projectPath: string, branchName: string): boolean {
  try {
    execSync(`git checkout -b ${branchName}`, {
      cwd: projectPath,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

export function stageFiles(projectPath: string, files: string[] = ['.']): boolean {
  try {
    execSync(`git add ${files.join(' ')}`, {
      cwd: projectPath,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

export function commit(projectPath: string, message: string): string | null {
  try {
    execSync(`git commit -m "${message}"`, {
      cwd: projectPath,
      encoding: 'utf-8',
    });
    const commitHash = execSync('git rev-parse HEAD', {
      cwd: projectPath,
      encoding: 'utf-8',
    }).trim();
    return commitHash;
  } catch {
    return null;
  }
}

export function pushBranch(projectPath: string, branchName: string, setUpstream: boolean = true): boolean {
  try {
    const upstreamFlag = setUpstream ? '-u' : '';
    execSync(`git push ${upstreamFlag} origin ${branchName}`, {
      cwd: projectPath,
      stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

export function createMergeRequest(
  projectPath: string,
  sourceBranch: string,
  targetBranch: string = 'main',
  title?: string,
  description?: string
): string | null {
  const remoteUrl = getRemoteUrl(projectPath);
  if (!remoteUrl) {
    return null;
  }

  if (remoteUrl.includes('github.com')) {
    return createGitHubMR(projectPath, sourceBranch, targetBranch, title, description);
  } else if (remoteUrl.includes('gitlab.com')) {
    return createGitLabMR(projectPath, sourceBranch, targetBranch, title, description);
  }

  return null;
}

function createGitHubMR(
  projectPath: string,
  sourceBranch: string,
  targetBranch: string,
  title?: string,
  description?: string
): string | null {
  const defaultTitle = `fix: resolve vulnerabilities in ${sourceBranch}`;
  const mrTitle = title || defaultTitle;
  const mrDesc = description || 'Auto-generated by Patcha CLI';

  try {
    const { execSync } = require('child_process');
    execSync(`gh pr create --title "${mrTitle}" --body "${mrDesc}" --base ${targetBranch} --head ${sourceBranch}`, {
      cwd: projectPath,
      stdio: 'ignore',
    });
    return `https://github.com/.../pull/new/${sourceBranch}`;
  } catch {
    return null;
  }
}

function createGitLabMR(
  projectPath: string,
  sourceBranch: string,
  targetBranch: string,
  title?: string,
  description?: string
): string | null {
  const remoteUrl = getRemoteUrl(projectPath);
  if (!remoteUrl) return null;

  const projectPathEncoded = remoteUrl
    .replace(/.*\/([^/]+)\.git$/, '$1')
    .replace(/\//g, '%2F');

  const defaultTitle = `fix: resolve vulnerabilities in ${sourceBranch}`;
  const mrTitle = title || defaultTitle;
  const mrDesc = description || 'Auto-generated by Patcha CLI';

  try {
    const { execSync } = require('child_process');
    execSync(
      `glab mr create --title "${mrTitle}" --description "${mrDesc}" --target-branch ${targetBranch} --yes`,
      {
        cwd: projectPath,
        stdio: 'ignore',
      }
    );
    return `https://gitlab.com/${projectPathEncoded}/-/merge_requests/new?merge_request%5Bsource_branch%5D=${sourceBranch}`;
  } catch {
    return null;
  }
}

export async function applyFixesWithGit(options: GitOptions): Promise<GitResult> {
  const { projectPath, createMR, mrTitle, mrDescription } = options;

  if (!isGitRepository(projectPath)) {
    return {
      success: false,
      message: 'Not a git repository',
    };
  }

  const currentBranch = getCurrentBranch(projectPath);
  const timestamp = Date.now();
  const branchName = `patcha/fix-${timestamp}`;

  if (!createBranch(projectPath, branchName)) {
    return {
      success: false,
      message: 'Failed to create branch',
    };
  }

  if (!stageFiles(projectPath)) {
    return {
      success: false,
      message: 'Failed to stage files',
      branch: branchName,
    };
  }

  const commitMessage = 'fix: resolve vulnerabilities\n\nAuto-generated by Patcha CLI';
  const commitHash = commit(projectPath, commitMessage);

  if (!commitHash) {
    return {
      success: false,
      message: 'Failed to commit changes',
      branch: branchName,
    };
  }

  if (!pushBranch(projectPath, branchName)) {
    return {
      success: false,
      message: 'Failed to push branch',
      branch: branchName,
      commit: commitHash,
    };
  }

  let mrUrl: string | undefined;
  if (createMR) {
    const targetBranch = currentBranch === 'main' ? 'main' : 'main';
    const result = createMergeRequest(projectPath, branchName, targetBranch, mrTitle, mrDescription);
    if (result) {
      mrUrl = result;
    }
  }

  return {
    success: true,
    branch: branchName,
    commit: commitHash,
    mrUrl,
  };
}
